app: paediatricbariatric
region: eu-west-1
# http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html
solution_stack_name: 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.0 (Puma)

development:
  strategy: inplace_update
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.micro

production:
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.small